name: build-pypi
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Build manylinux pypi dist
      uses: ./.github/actions/build-pypi-manylinux


    - name: Publish distribution to Test PyPI
      if: contains(github.event.ref, '-test')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
        packages_dir: python/dist

    - name: Publish distribution to PyPI
      # not sure how to use "not"
      if: contains(github.event.ref, '-test') == false
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.pypi_password }}
        packages_dir: python/dist
