name: build
on: [push]

jobs:
  # Build wheels on all platforms ########################################################
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Docker login
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: docker login docker.pkg.github.com --username "${GITHUB_ACTOR}" --password "${GITHUB_TOKEN}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.7'

    - name: Build wheels
      env:
        CIBW_MANYLINUX_X86_64_IMAGE: docker.pkg.github.com/chatziko/libqif/manylinux:v6
        CIBW_BEFORE_ALL_LINUX: bash .github/workflows/ubuntu-build-qif.sh
        CIBW_BEFORE_ALL_MACOS: bash .github/workflows/macos-build-qif.sh
        CIBW_ENVIRONMENT: "TMPDIR=$PWD"
        CIBW_BUILD: "cp3?-*_x86_64"
      run: |
        python -m pip install cibuildwheel==1.7.1
        python -m cibuildwheel --output-dir wheelhouse python_lib

    - uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./wheelhouse/*.whl


  # Upload wheels to PyPI ##########################################################
  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
          path: dist

      - uses: pypa/gh-action-pypi-publish@master
        if: ${{ !contains(github.event.ref, '-test') }}
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}

      - uses: pypa/gh-action-pypi-publish@master
        if: contains(github.event.ref, '-test')
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/